/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BatchSchema extends BaseModel {
  static $columns = ['batchNumber', 'costPrice', 'createdAt', 'deletedAt', 'expiryDate', 'id', 'productId', 'quantity', 'receivedDate', 'sellingPrice', 'status', 'updatedAt', 'userId'] as const
  $columns = BatchSchema.$columns
  @column()
  declare batchNumber: string
  @column()
  declare costPrice: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.date()
  declare expiryDate: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare quantity: number
  @column.date()
  declare receivedDate: DateTime
  @column()
  declare sellingPrice: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ProductSchema extends BaseModel {
  static $columns = ['barcode', 'category', 'createdAt', 'deletedAt', 'id', 'minStockAlert', 'name', 'unit', 'updatedAt', 'userId'] as const
  $columns = ProductSchema.$columns
  @column()
  declare barcode: string
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare minStockAlert: number
  @column()
  declare name: string
  @column()
  declare unit: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class SaleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'invoiceNo', 'paymentMethod', 'totalAmount', 'userId'] as const
  $columns = SaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare invoiceNo: string
  @column()
  declare paymentMethod: string
  @column()
  declare totalAmount: string
  @column()
  declare userId: string
}

export class SaleItemSchema extends BaseModel {
  static $columns = ['batchId', 'id', 'productId', 'quantity', 'saleId', 'subtotal', 'unitPrice'] as const
  $columns = SaleItemSchema.$columns
  @column()
  declare batchId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare quantity: number
  @column()
  declare saleId: string
  @column()
  declare subtotal: string
  @column()
  declare unitPrice: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'role', 'storeName', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare storeName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
